development:
  adapter: postgresql
  encoding: unicode
  database: auth
  host: db
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: auth_test
  pool: 5
  username: postgres
  password:
  host: db