source 'https://rubygems.org'

gem 'rake'
gem 'hanami',       '~> 1.3'
gem 'hanami-model', '~> 1.3'

gem 'pg'

gem 'slim'
gem 'hanami-bootstrap'
gem 'jquery-hanami'
gem 'dry-monads'
gem 'omniauth'
gem "omniauth-accounts"
gem "karafka"
gem 'dry-configurable', '0.8'
gem 'schema_registry', path: '../schema_registry'

group :development do
  # Code reloading
  # See: https://guides.hanamirb.org/projects/code-reloading
  gem 'shotgun', platforms: :ruby
  gem 'hanami-webconsole'
  gem 'ruby_jard'
end

group :test, :development do
  gem 'dotenv', '~> 2.4'
end

group :test do
  gem 'rspec'
  gem 'capybara'
end

group :production do
  gem 'puma'
end
