
@startuml Handle Async audit log message(task completed)
    start
    :receive the message that employee finished the task;
    :accrue an amount to the user;
    note right
        balance??
        balance moves to the next day
    end note
    :increment the counter for total earned amount for a day(for a user);
    if (it's very expensive task?) then(yes)
        :mark as very expensive task for the day;
    endif
    :reduce the counter of how many management earned for the day;
    end
@enduml

@startuml Handl Async audit log message(task assigned)
    start
    :receive the message that task is assigned;
    :charge an employee on the assigment cost;
    end
@enduml

@startuml Handle Async audit log message(task created)
    start
    :receive the message that task is created;
    :calculate task fee;
    note right
        rand(-10..-20)$
    end note
    :calculate the task amount;
    note right
        rand(20..40)$
    end note
    :change task state to calculated;
@enduml

@startuml Handle Async audit log message(task fee)
    start
    :receive the message that a task is assigned;
    :increase the counter of how many management earned for the day;
    if (it's very expensive task?) then(yes)
        :mark as very expensive task for the day;
    endif
    end
@enduml


@startuml Handle Async audit log message(invoice paid)
    start
    :set user balance = 0 ;
    end
@enduml
