@startuml High-level-architecture
storage Tasker
storage Analytics
storage EndDayProcessor
storage Autheticator
storage Accouting
storage TasksUI
storage AccountingUI
storage Auditor
storage AnalyticsUI
queue EventsBus

TasksUI -- Autheticator
AccountingUI -- Autheticator
AnalyticsUI -- Autheticator

Autheticator -- Tasker
Autheticator -- Analytics
Autheticator -- Accouting

Tasker -- EventsBus
EventsBus -- Auditor
Analytics -- EventsBus
Accouting -- EventsBus
EndDayProcessor -- EventsBus
@enduml