@startuml data_model

rectangle User
rectangle "User role" as ur
rectangle "User auth information" as uai
rectangle "User Balance" as ub
rectangle "User Balance audit" as uba

rectangle UserEarnPerDay
rectangle ManagerEarnPerDay
rectangle ManagersLosePerDay

rectangle Task
rectangle Status
rectangle Amount
rectangle AssignFee

User --> ur
User --> uai
User --> ub
User --> uba
User --> Task
Task --> Status
Task --> Amount
Task --> AssignFee
Task ---> uba
uba --> UserEarnPerDay
uba --> ManagerEarnPerDay
uba --> ManagersLosePerDay
@enduml