@startuml data_model

rectangle User
rectangle "User role" as ur
rectangle "User auth information" as uai
rectangle "User Balance" as ub
rectangle "User Balance audit" as uba

rectangle UserEarnPerDay
rectangle ManagerEarnPerDay
rectangle ManagersLosePerDay

rectangle Task
rectangle AssignedUserID
rectangle Status
rectangle Amount
rectangle AssignFee
rectangle ApplyFeeAmountLog
rectangle ApplyAmountLog

AssignFee --> ApplyFeeAmountLog
Amount --> ApplyAmountLog
User --> ur
User --> uai
User --> ub
User --> uba
User --> Task
Task --> AssignedUserID
Task --> Status
Task --> Amount
Task --> AssignFee
Task --> ApplyFeeAmountLog
Task --> ApplyAmountLog
uba --> UserEarnPerDay
uba --> ManagerEarnPerDay
uba --> ManagersLosePerDay
@enduml
